services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: docker
      MONGO_INITDB_DATABASE: hoagie-hub
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: